name: run-tests

on:
  push:
    paths: ['**.php', '.github/workflows/run-tests.yml', 'phpunit.xml.dist', 'composer.json']
  pull_request:
    paths: ['**.php', '.github/workflows/run-tests.yml', 'phpunit.xml.dist', 'composer.json']

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: true
      matrix:
        php: [8.4, 8.5]
        stability: [prefer-lowest, prefer-stable]

    name: P${{ matrix.php }} - L13 - ${{ matrix.stability }}

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none

      - run: composer update --${{ matrix.stability }} --prefer-dist --no-interaction

      - run: vendor/bin/pest --ci
